// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.24.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Metadata> getMetadata({required String path, dynamic hint}) =>
    RustLib.instance.api.getMetadata(path: path, hint: hint);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<Tag>>
@sealed
class Tag extends RustOpaque {
  Tag.dcoDecode(List<dynamic> wire) : super.dcoDecode(wire, _kStaticData);

  Tag.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Tag,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Tag,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TagPtr,
  );
}

class Metadata {
  final Tag? tag;
  final Uint8List? art;
  final String? title;

  const Metadata({
    this.tag,
    this.art,
    this.title,
  });

  @override
  int get hashCode => tag.hashCode ^ art.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Metadata &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          art == other.art &&
          title == other.title;
}
