// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.24.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<Track>> getMusicFiles({dynamic hint}) =>
    RustLib.instance.api.getMusicFiles(hint: hint);

class Track {
  final String name;
  final String path;
  final int? id;

  const Track({
    required this.name,
    required this.path,
    this.id,
  });

  @override
  int get hashCode => name.hashCode ^ path.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          id == other.id;
}
